---
title: "Vignette 2 - Inputs"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette 2 - Inputs}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This vignette discusses the format used for model input data by this package. Population and vaccination data for one or more regions to be considered are stored in a list object along with a list of regions, the years included, and the age groups into which the population is divided. 

Here an example data set is loaded from the package:

```{r,eval=FALSE}
library(YellowFeverDynamics)
input_data_all <- readRDS(file=paste(path.package("YellowFeverDynamics"),"/inst/exdata/input_data_example.Rds",sep=""))
```

[TBA]

```{r,eval=FALSE}
names(input_data_all)
```
[TBA]

```{r,eval=FALSE}
input_data_all$region_labels
```

[TBA]

```{r,eval=FALSE}
input_data_all$years_labels
```

[TBA]

```{r,eval=FALSE}
input_data_all$age_labels
```
