// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// BasicModelOD.cpp
SEXP dust_BasicModelOD_alloc(cpp11::list r_pars, bool pars_multi, size_t step, cpp11::sexp r_n_particles, size_t n_threads, cpp11::sexp r_seed, cpp11::sexp device_id);
extern "C" SEXP _YellowFeverDynamics_dust_BasicModelOD_alloc(SEXP r_pars, SEXP pars_multi, SEXP step, SEXP r_n_particles, SEXP n_threads, SEXP r_seed, SEXP device_id) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_BasicModelOD_alloc(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<bool>>(pars_multi), cpp11::as_cpp<cpp11::decay_t<size_t>>(step), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_particles), cpp11::as_cpp<cpp11::decay_t<size_t>>(n_threads), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_seed), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(device_id)));
  END_CPP11
}
// BasicModelOD.cpp
SEXP dust_BasicModelOD_run(SEXP ptr, size_t step_end, bool device);
extern "C" SEXP _YellowFeverDynamics_dust_BasicModelOD_run(SEXP ptr, SEXP step_end, SEXP device) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_BasicModelOD_run(cpp11::as_cpp<cpp11::decay_t<SEXP>>(ptr), cpp11::as_cpp<cpp11::decay_t<size_t>>(step_end), cpp11::as_cpp<cpp11::decay_t<bool>>(device)));
  END_CPP11
}
// BasicModelOD.cpp
SEXP dust_BasicModelOD_simulate(SEXP ptr, cpp11::sexp step_end, bool device);
extern "C" SEXP _YellowFeverDynamics_dust_BasicModelOD_simulate(SEXP ptr, SEXP step_end, SEXP device) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_BasicModelOD_simulate(cpp11::as_cpp<cpp11::decay_t<SEXP>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(step_end), cpp11::as_cpp<cpp11::decay_t<bool>>(device)));
  END_CPP11
}
// BasicModelOD.cpp
SEXP dust_BasicModelOD_set_index(SEXP ptr, cpp11::sexp r_index);
extern "C" SEXP _YellowFeverDynamics_dust_BasicModelOD_set_index(SEXP ptr, SEXP r_index) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_BasicModelOD_set_index(cpp11::as_cpp<cpp11::decay_t<SEXP>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index)));
  END_CPP11
}
// BasicModelOD.cpp
SEXP dust_BasicModelOD_set_state(SEXP ptr, SEXP r_state, SEXP r_step);
extern "C" SEXP _YellowFeverDynamics_dust_BasicModelOD_set_state(SEXP ptr, SEXP r_state, SEXP r_step) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_BasicModelOD_set_state(cpp11::as_cpp<cpp11::decay_t<SEXP>>(ptr), cpp11::as_cpp<cpp11::decay_t<SEXP>>(r_state), cpp11::as_cpp<cpp11::decay_t<SEXP>>(r_step)));
  END_CPP11
}
// BasicModelOD.cpp
SEXP dust_BasicModelOD_reset(SEXP ptr, cpp11::list r_pars, size_t step);
extern "C" SEXP _YellowFeverDynamics_dust_BasicModelOD_reset(SEXP ptr, SEXP r_pars, SEXP step) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_BasicModelOD_reset(cpp11::as_cpp<cpp11::decay_t<SEXP>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<size_t>>(step)));
  END_CPP11
}
// BasicModelOD.cpp
SEXP dust_BasicModelOD_state(SEXP ptr, SEXP r_index);
extern "C" SEXP _YellowFeverDynamics_dust_BasicModelOD_state(SEXP ptr, SEXP r_index) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_BasicModelOD_state(cpp11::as_cpp<cpp11::decay_t<SEXP>>(ptr), cpp11::as_cpp<cpp11::decay_t<SEXP>>(r_index)));
  END_CPP11
}
// BasicModelOD.cpp
size_t dust_BasicModelOD_step(SEXP ptr);
extern "C" SEXP _YellowFeverDynamics_dust_BasicModelOD_step(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_BasicModelOD_step(cpp11::as_cpp<cpp11::decay_t<SEXP>>(ptr)));
  END_CPP11
}
// BasicModelOD.cpp
void dust_BasicModelOD_reorder(SEXP ptr, cpp11::sexp r_index);
extern "C" SEXP _YellowFeverDynamics_dust_BasicModelOD_reorder(SEXP ptr, SEXP r_index) {
  BEGIN_CPP11
    dust_BasicModelOD_reorder(cpp11::as_cpp<cpp11::decay_t<SEXP>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index));
    return R_NilValue;
  END_CPP11
}
// BasicModelOD.cpp
SEXP dust_BasicModelOD_resample(SEXP ptr, cpp11::doubles r_weights);
extern "C" SEXP _YellowFeverDynamics_dust_BasicModelOD_resample(SEXP ptr, SEXP r_weights) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_BasicModelOD_resample(cpp11::as_cpp<cpp11::decay_t<SEXP>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(r_weights)));
  END_CPP11
}
// BasicModelOD.cpp
SEXP dust_BasicModelOD_set_pars(SEXP ptr, cpp11::list r_pars);
extern "C" SEXP _YellowFeverDynamics_dust_BasicModelOD_set_pars(SEXP ptr, SEXP r_pars) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_BasicModelOD_set_pars(cpp11::as_cpp<cpp11::decay_t<SEXP>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars)));
  END_CPP11
}
// BasicModelOD.cpp
SEXP dust_BasicModelOD_rng_state(SEXP ptr, bool first_only, bool last_only);
extern "C" SEXP _YellowFeverDynamics_dust_BasicModelOD_rng_state(SEXP ptr, SEXP first_only, SEXP last_only) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_BasicModelOD_rng_state(cpp11::as_cpp<cpp11::decay_t<SEXP>>(ptr), cpp11::as_cpp<cpp11::decay_t<bool>>(first_only), cpp11::as_cpp<cpp11::decay_t<bool>>(last_only)));
  END_CPP11
}
// BasicModelOD.cpp
SEXP dust_BasicModelOD_set_rng_state(SEXP ptr, cpp11::raws rng_state);
extern "C" SEXP _YellowFeverDynamics_dust_BasicModelOD_set_rng_state(SEXP ptr, SEXP rng_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_BasicModelOD_set_rng_state(cpp11::as_cpp<cpp11::decay_t<SEXP>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::raws>>(rng_state)));
  END_CPP11
}
// BasicModelOD.cpp
SEXP dust_BasicModelOD_set_data(SEXP ptr, cpp11::list data);
extern "C" SEXP _YellowFeverDynamics_dust_BasicModelOD_set_data(SEXP ptr, SEXP data) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_BasicModelOD_set_data(cpp11::as_cpp<cpp11::decay_t<SEXP>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(data)));
  END_CPP11
}
// BasicModelOD.cpp
SEXP dust_BasicModelOD_compare_data(SEXP ptr, bool device);
extern "C" SEXP _YellowFeverDynamics_dust_BasicModelOD_compare_data(SEXP ptr, SEXP device) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_BasicModelOD_compare_data(cpp11::as_cpp<cpp11::decay_t<SEXP>>(ptr), cpp11::as_cpp<cpp11::decay_t<bool>>(device)));
  END_CPP11
}
// BasicModelOD.cpp
SEXP dust_BasicModelOD_filter(SEXP ptr, bool save_trajectories, cpp11::sexp step_snapshot, bool device);
extern "C" SEXP _YellowFeverDynamics_dust_BasicModelOD_filter(SEXP ptr, SEXP save_trajectories, SEXP step_snapshot, SEXP device) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_BasicModelOD_filter(cpp11::as_cpp<cpp11::decay_t<SEXP>>(ptr), cpp11::as_cpp<cpp11::decay_t<bool>>(save_trajectories), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(step_snapshot), cpp11::as_cpp<cpp11::decay_t<bool>>(device)));
  END_CPP11
}
// BasicModelOD.cpp
cpp11::sexp dust_BasicModelOD_capabilities();
extern "C" SEXP _YellowFeverDynamics_dust_BasicModelOD_capabilities() {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_BasicModelOD_capabilities());
  END_CPP11
}
// BasicModelOD.cpp
void dust_BasicModelOD_set_n_threads(SEXP ptr, int n_threads);
extern "C" SEXP _YellowFeverDynamics_dust_BasicModelOD_set_n_threads(SEXP ptr, SEXP n_threads) {
  BEGIN_CPP11
    dust_BasicModelOD_set_n_threads(cpp11::as_cpp<cpp11::decay_t<SEXP>>(ptr), cpp11::as_cpp<cpp11::decay_t<int>>(n_threads));
    return R_NilValue;
  END_CPP11
}
// BasicModelOD.cpp
int dust_BasicModelOD_n_state(SEXP ptr);
extern "C" SEXP _YellowFeverDynamics_dust_BasicModelOD_n_state(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_BasicModelOD_n_state(cpp11::as_cpp<cpp11::decay_t<SEXP>>(ptr)));
  END_CPP11
}
// BasicModelOD.cpp
cpp11::sexp dust_BasicModelOD_device_info();
extern "C" SEXP _YellowFeverDynamics_dust_BasicModelOD_device_info() {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_BasicModelOD_device_info());
  END_CPP11
}
// FullModelOD.cpp
SEXP dust_FullModelOD_alloc(cpp11::list r_pars, bool pars_multi, size_t step, cpp11::sexp r_n_particles, size_t n_threads, cpp11::sexp r_seed, cpp11::sexp device_id);
extern "C" SEXP _YellowFeverDynamics_dust_FullModelOD_alloc(SEXP r_pars, SEXP pars_multi, SEXP step, SEXP r_n_particles, SEXP n_threads, SEXP r_seed, SEXP device_id) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_FullModelOD_alloc(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<bool>>(pars_multi), cpp11::as_cpp<cpp11::decay_t<size_t>>(step), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_particles), cpp11::as_cpp<cpp11::decay_t<size_t>>(n_threads), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_seed), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(device_id)));
  END_CPP11
}
// FullModelOD.cpp
SEXP dust_FullModelOD_run(SEXP ptr, size_t step_end, bool device);
extern "C" SEXP _YellowFeverDynamics_dust_FullModelOD_run(SEXP ptr, SEXP step_end, SEXP device) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_FullModelOD_run(cpp11::as_cpp<cpp11::decay_t<SEXP>>(ptr), cpp11::as_cpp<cpp11::decay_t<size_t>>(step_end), cpp11::as_cpp<cpp11::decay_t<bool>>(device)));
  END_CPP11
}
// FullModelOD.cpp
SEXP dust_FullModelOD_simulate(SEXP ptr, cpp11::sexp step_end, bool device);
extern "C" SEXP _YellowFeverDynamics_dust_FullModelOD_simulate(SEXP ptr, SEXP step_end, SEXP device) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_FullModelOD_simulate(cpp11::as_cpp<cpp11::decay_t<SEXP>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(step_end), cpp11::as_cpp<cpp11::decay_t<bool>>(device)));
  END_CPP11
}
// FullModelOD.cpp
SEXP dust_FullModelOD_set_index(SEXP ptr, cpp11::sexp r_index);
extern "C" SEXP _YellowFeverDynamics_dust_FullModelOD_set_index(SEXP ptr, SEXP r_index) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_FullModelOD_set_index(cpp11::as_cpp<cpp11::decay_t<SEXP>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index)));
  END_CPP11
}
// FullModelOD.cpp
SEXP dust_FullModelOD_set_state(SEXP ptr, SEXP r_state, SEXP r_step);
extern "C" SEXP _YellowFeverDynamics_dust_FullModelOD_set_state(SEXP ptr, SEXP r_state, SEXP r_step) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_FullModelOD_set_state(cpp11::as_cpp<cpp11::decay_t<SEXP>>(ptr), cpp11::as_cpp<cpp11::decay_t<SEXP>>(r_state), cpp11::as_cpp<cpp11::decay_t<SEXP>>(r_step)));
  END_CPP11
}
// FullModelOD.cpp
SEXP dust_FullModelOD_reset(SEXP ptr, cpp11::list r_pars, size_t step);
extern "C" SEXP _YellowFeverDynamics_dust_FullModelOD_reset(SEXP ptr, SEXP r_pars, SEXP step) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_FullModelOD_reset(cpp11::as_cpp<cpp11::decay_t<SEXP>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<size_t>>(step)));
  END_CPP11
}
// FullModelOD.cpp
SEXP dust_FullModelOD_state(SEXP ptr, SEXP r_index);
extern "C" SEXP _YellowFeverDynamics_dust_FullModelOD_state(SEXP ptr, SEXP r_index) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_FullModelOD_state(cpp11::as_cpp<cpp11::decay_t<SEXP>>(ptr), cpp11::as_cpp<cpp11::decay_t<SEXP>>(r_index)));
  END_CPP11
}
// FullModelOD.cpp
size_t dust_FullModelOD_step(SEXP ptr);
extern "C" SEXP _YellowFeverDynamics_dust_FullModelOD_step(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_FullModelOD_step(cpp11::as_cpp<cpp11::decay_t<SEXP>>(ptr)));
  END_CPP11
}
// FullModelOD.cpp
void dust_FullModelOD_reorder(SEXP ptr, cpp11::sexp r_index);
extern "C" SEXP _YellowFeverDynamics_dust_FullModelOD_reorder(SEXP ptr, SEXP r_index) {
  BEGIN_CPP11
    dust_FullModelOD_reorder(cpp11::as_cpp<cpp11::decay_t<SEXP>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index));
    return R_NilValue;
  END_CPP11
}
// FullModelOD.cpp
SEXP dust_FullModelOD_resample(SEXP ptr, cpp11::doubles r_weights);
extern "C" SEXP _YellowFeverDynamics_dust_FullModelOD_resample(SEXP ptr, SEXP r_weights) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_FullModelOD_resample(cpp11::as_cpp<cpp11::decay_t<SEXP>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(r_weights)));
  END_CPP11
}
// FullModelOD.cpp
SEXP dust_FullModelOD_set_pars(SEXP ptr, cpp11::list r_pars);
extern "C" SEXP _YellowFeverDynamics_dust_FullModelOD_set_pars(SEXP ptr, SEXP r_pars) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_FullModelOD_set_pars(cpp11::as_cpp<cpp11::decay_t<SEXP>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars)));
  END_CPP11
}
// FullModelOD.cpp
SEXP dust_FullModelOD_rng_state(SEXP ptr, bool first_only, bool last_only);
extern "C" SEXP _YellowFeverDynamics_dust_FullModelOD_rng_state(SEXP ptr, SEXP first_only, SEXP last_only) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_FullModelOD_rng_state(cpp11::as_cpp<cpp11::decay_t<SEXP>>(ptr), cpp11::as_cpp<cpp11::decay_t<bool>>(first_only), cpp11::as_cpp<cpp11::decay_t<bool>>(last_only)));
  END_CPP11
}
// FullModelOD.cpp
SEXP dust_FullModelOD_set_rng_state(SEXP ptr, cpp11::raws rng_state);
extern "C" SEXP _YellowFeverDynamics_dust_FullModelOD_set_rng_state(SEXP ptr, SEXP rng_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_FullModelOD_set_rng_state(cpp11::as_cpp<cpp11::decay_t<SEXP>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::raws>>(rng_state)));
  END_CPP11
}
// FullModelOD.cpp
SEXP dust_FullModelOD_set_data(SEXP ptr, cpp11::list data);
extern "C" SEXP _YellowFeverDynamics_dust_FullModelOD_set_data(SEXP ptr, SEXP data) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_FullModelOD_set_data(cpp11::as_cpp<cpp11::decay_t<SEXP>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(data)));
  END_CPP11
}
// FullModelOD.cpp
SEXP dust_FullModelOD_compare_data(SEXP ptr, bool device);
extern "C" SEXP _YellowFeverDynamics_dust_FullModelOD_compare_data(SEXP ptr, SEXP device) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_FullModelOD_compare_data(cpp11::as_cpp<cpp11::decay_t<SEXP>>(ptr), cpp11::as_cpp<cpp11::decay_t<bool>>(device)));
  END_CPP11
}
// FullModelOD.cpp
SEXP dust_FullModelOD_filter(SEXP ptr, bool save_trajectories, cpp11::sexp step_snapshot, bool device);
extern "C" SEXP _YellowFeverDynamics_dust_FullModelOD_filter(SEXP ptr, SEXP save_trajectories, SEXP step_snapshot, SEXP device) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_FullModelOD_filter(cpp11::as_cpp<cpp11::decay_t<SEXP>>(ptr), cpp11::as_cpp<cpp11::decay_t<bool>>(save_trajectories), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(step_snapshot), cpp11::as_cpp<cpp11::decay_t<bool>>(device)));
  END_CPP11
}
// FullModelOD.cpp
cpp11::sexp dust_FullModelOD_capabilities();
extern "C" SEXP _YellowFeverDynamics_dust_FullModelOD_capabilities() {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_FullModelOD_capabilities());
  END_CPP11
}
// FullModelOD.cpp
void dust_FullModelOD_set_n_threads(SEXP ptr, int n_threads);
extern "C" SEXP _YellowFeverDynamics_dust_FullModelOD_set_n_threads(SEXP ptr, SEXP n_threads) {
  BEGIN_CPP11
    dust_FullModelOD_set_n_threads(cpp11::as_cpp<cpp11::decay_t<SEXP>>(ptr), cpp11::as_cpp<cpp11::decay_t<int>>(n_threads));
    return R_NilValue;
  END_CPP11
}
// FullModelOD.cpp
int dust_FullModelOD_n_state(SEXP ptr);
extern "C" SEXP _YellowFeverDynamics_dust_FullModelOD_n_state(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_FullModelOD_n_state(cpp11::as_cpp<cpp11::decay_t<SEXP>>(ptr)));
  END_CPP11
}
// FullModelOD.cpp
cpp11::sexp dust_FullModelOD_device_info();
extern "C" SEXP _YellowFeverDynamics_dust_FullModelOD_device_info() {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_FullModelOD_device_info());
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_YellowFeverDynamics_dust_BasicModelOD_alloc",         (DL_FUNC) &_YellowFeverDynamics_dust_BasicModelOD_alloc,         7},
    {"_YellowFeverDynamics_dust_BasicModelOD_capabilities",  (DL_FUNC) &_YellowFeverDynamics_dust_BasicModelOD_capabilities,  0},
    {"_YellowFeverDynamics_dust_BasicModelOD_compare_data",  (DL_FUNC) &_YellowFeverDynamics_dust_BasicModelOD_compare_data,  2},
    {"_YellowFeverDynamics_dust_BasicModelOD_device_info",   (DL_FUNC) &_YellowFeverDynamics_dust_BasicModelOD_device_info,   0},
    {"_YellowFeverDynamics_dust_BasicModelOD_filter",        (DL_FUNC) &_YellowFeverDynamics_dust_BasicModelOD_filter,        4},
    {"_YellowFeverDynamics_dust_BasicModelOD_n_state",       (DL_FUNC) &_YellowFeverDynamics_dust_BasicModelOD_n_state,       1},
    {"_YellowFeverDynamics_dust_BasicModelOD_reorder",       (DL_FUNC) &_YellowFeverDynamics_dust_BasicModelOD_reorder,       2},
    {"_YellowFeverDynamics_dust_BasicModelOD_resample",      (DL_FUNC) &_YellowFeverDynamics_dust_BasicModelOD_resample,      2},
    {"_YellowFeverDynamics_dust_BasicModelOD_reset",         (DL_FUNC) &_YellowFeverDynamics_dust_BasicModelOD_reset,         3},
    {"_YellowFeverDynamics_dust_BasicModelOD_rng_state",     (DL_FUNC) &_YellowFeverDynamics_dust_BasicModelOD_rng_state,     3},
    {"_YellowFeverDynamics_dust_BasicModelOD_run",           (DL_FUNC) &_YellowFeverDynamics_dust_BasicModelOD_run,           3},
    {"_YellowFeverDynamics_dust_BasicModelOD_set_data",      (DL_FUNC) &_YellowFeverDynamics_dust_BasicModelOD_set_data,      2},
    {"_YellowFeverDynamics_dust_BasicModelOD_set_index",     (DL_FUNC) &_YellowFeverDynamics_dust_BasicModelOD_set_index,     2},
    {"_YellowFeverDynamics_dust_BasicModelOD_set_n_threads", (DL_FUNC) &_YellowFeverDynamics_dust_BasicModelOD_set_n_threads, 2},
    {"_YellowFeverDynamics_dust_BasicModelOD_set_pars",      (DL_FUNC) &_YellowFeverDynamics_dust_BasicModelOD_set_pars,      2},
    {"_YellowFeverDynamics_dust_BasicModelOD_set_rng_state", (DL_FUNC) &_YellowFeverDynamics_dust_BasicModelOD_set_rng_state, 2},
    {"_YellowFeverDynamics_dust_BasicModelOD_set_state",     (DL_FUNC) &_YellowFeverDynamics_dust_BasicModelOD_set_state,     3},
    {"_YellowFeverDynamics_dust_BasicModelOD_simulate",      (DL_FUNC) &_YellowFeverDynamics_dust_BasicModelOD_simulate,      3},
    {"_YellowFeverDynamics_dust_BasicModelOD_state",         (DL_FUNC) &_YellowFeverDynamics_dust_BasicModelOD_state,         2},
    {"_YellowFeverDynamics_dust_BasicModelOD_step",          (DL_FUNC) &_YellowFeverDynamics_dust_BasicModelOD_step,          1},
    {"_YellowFeverDynamics_dust_FullModelOD_alloc",          (DL_FUNC) &_YellowFeverDynamics_dust_FullModelOD_alloc,          7},
    {"_YellowFeverDynamics_dust_FullModelOD_capabilities",   (DL_FUNC) &_YellowFeverDynamics_dust_FullModelOD_capabilities,   0},
    {"_YellowFeverDynamics_dust_FullModelOD_compare_data",   (DL_FUNC) &_YellowFeverDynamics_dust_FullModelOD_compare_data,   2},
    {"_YellowFeverDynamics_dust_FullModelOD_device_info",    (DL_FUNC) &_YellowFeverDynamics_dust_FullModelOD_device_info,    0},
    {"_YellowFeverDynamics_dust_FullModelOD_filter",         (DL_FUNC) &_YellowFeverDynamics_dust_FullModelOD_filter,         4},
    {"_YellowFeverDynamics_dust_FullModelOD_n_state",        (DL_FUNC) &_YellowFeverDynamics_dust_FullModelOD_n_state,        1},
    {"_YellowFeverDynamics_dust_FullModelOD_reorder",        (DL_FUNC) &_YellowFeverDynamics_dust_FullModelOD_reorder,        2},
    {"_YellowFeverDynamics_dust_FullModelOD_resample",       (DL_FUNC) &_YellowFeverDynamics_dust_FullModelOD_resample,       2},
    {"_YellowFeverDynamics_dust_FullModelOD_reset",          (DL_FUNC) &_YellowFeverDynamics_dust_FullModelOD_reset,          3},
    {"_YellowFeverDynamics_dust_FullModelOD_rng_state",      (DL_FUNC) &_YellowFeverDynamics_dust_FullModelOD_rng_state,      3},
    {"_YellowFeverDynamics_dust_FullModelOD_run",            (DL_FUNC) &_YellowFeverDynamics_dust_FullModelOD_run,            3},
    {"_YellowFeverDynamics_dust_FullModelOD_set_data",       (DL_FUNC) &_YellowFeverDynamics_dust_FullModelOD_set_data,       2},
    {"_YellowFeverDynamics_dust_FullModelOD_set_index",      (DL_FUNC) &_YellowFeverDynamics_dust_FullModelOD_set_index,      2},
    {"_YellowFeverDynamics_dust_FullModelOD_set_n_threads",  (DL_FUNC) &_YellowFeverDynamics_dust_FullModelOD_set_n_threads,  2},
    {"_YellowFeverDynamics_dust_FullModelOD_set_pars",       (DL_FUNC) &_YellowFeverDynamics_dust_FullModelOD_set_pars,       2},
    {"_YellowFeverDynamics_dust_FullModelOD_set_rng_state",  (DL_FUNC) &_YellowFeverDynamics_dust_FullModelOD_set_rng_state,  2},
    {"_YellowFeverDynamics_dust_FullModelOD_set_state",      (DL_FUNC) &_YellowFeverDynamics_dust_FullModelOD_set_state,      3},
    {"_YellowFeverDynamics_dust_FullModelOD_simulate",       (DL_FUNC) &_YellowFeverDynamics_dust_FullModelOD_simulate,       3},
    {"_YellowFeverDynamics_dust_FullModelOD_state",          (DL_FUNC) &_YellowFeverDynamics_dust_FullModelOD_state,          2},
    {"_YellowFeverDynamics_dust_FullModelOD_step",           (DL_FUNC) &_YellowFeverDynamics_dust_FullModelOD_step,           1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_YellowFeverDynamics(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
