# Generated by cpp11: do not edit by hand

dust_BasicModelOD_capabilities <- function() {
  .Call(`_YellowFeverDynamics_dust_BasicModelOD_capabilities`)
}

dust_BasicModelOD_gpu_info <- function() {
  .Call(`_YellowFeverDynamics_dust_BasicModelOD_gpu_info`)
}

dust_cpu_BasicModelOD_alloc <- function(r_pars, pars_multi, time, r_n_particles, n_threads, r_seed, deterministic, gpu_config) {
  .Call(`_YellowFeverDynamics_dust_cpu_BasicModelOD_alloc`, r_pars, pars_multi, time, r_n_particles, n_threads, r_seed, deterministic, gpu_config)
}

dust_cpu_BasicModelOD_run <- function(ptr, time_end) {
  .Call(`_YellowFeverDynamics_dust_cpu_BasicModelOD_run`, ptr, time_end)
}

dust_cpu_BasicModelOD_simulate <- function(ptr, time_end) {
  .Call(`_YellowFeverDynamics_dust_cpu_BasicModelOD_simulate`, ptr, time_end)
}

dust_cpu_BasicModelOD_set_index <- function(ptr, r_index) {
  .Call(`_YellowFeverDynamics_dust_cpu_BasicModelOD_set_index`, ptr, r_index)
}

dust_cpu_BasicModelOD_update_state <- function(ptr, r_pars, r_state, r_time, r_set_initial_state, index, reset_step_size) {
  .Call(`_YellowFeverDynamics_dust_cpu_BasicModelOD_update_state`, ptr, r_pars, r_state, r_time, r_set_initial_state, index, reset_step_size)
}

dust_cpu_BasicModelOD_state <- function(ptr, r_index) {
  .Call(`_YellowFeverDynamics_dust_cpu_BasicModelOD_state`, ptr, r_index)
}

dust_cpu_BasicModelOD_time <- function(ptr) {
  .Call(`_YellowFeverDynamics_dust_cpu_BasicModelOD_time`, ptr)
}

dust_cpu_BasicModelOD_reorder <- function(ptr, r_index) {
  invisible(.Call(`_YellowFeverDynamics_dust_cpu_BasicModelOD_reorder`, ptr, r_index))
}

dust_cpu_BasicModelOD_resample <- function(ptr, r_weights) {
  .Call(`_YellowFeverDynamics_dust_cpu_BasicModelOD_resample`, ptr, r_weights)
}

dust_cpu_BasicModelOD_rng_state <- function(ptr, first_only, last_only) {
  .Call(`_YellowFeverDynamics_dust_cpu_BasicModelOD_rng_state`, ptr, first_only, last_only)
}

dust_cpu_BasicModelOD_set_rng_state <- function(ptr, rng_state) {
  .Call(`_YellowFeverDynamics_dust_cpu_BasicModelOD_set_rng_state`, ptr, rng_state)
}

dust_cpu_BasicModelOD_set_data <- function(ptr, data, shared) {
  .Call(`_YellowFeverDynamics_dust_cpu_BasicModelOD_set_data`, ptr, data, shared)
}

dust_cpu_BasicModelOD_compare_data <- function(ptr) {
  .Call(`_YellowFeverDynamics_dust_cpu_BasicModelOD_compare_data`, ptr)
}

dust_cpu_BasicModelOD_filter <- function(ptr, time_end, save_trajectories, time_snapshot, min_log_likelihood) {
  .Call(`_YellowFeverDynamics_dust_cpu_BasicModelOD_filter`, ptr, time_end, save_trajectories, time_snapshot, min_log_likelihood)
}

dust_cpu_BasicModelOD_set_n_threads <- function(ptr, n_threads) {
  invisible(.Call(`_YellowFeverDynamics_dust_cpu_BasicModelOD_set_n_threads`, ptr, n_threads))
}

dust_cpu_BasicModelOD_n_state <- function(ptr) {
  .Call(`_YellowFeverDynamics_dust_cpu_BasicModelOD_n_state`, ptr)
}

dust_FullModelOD_capabilities <- function() {
  .Call(`_YellowFeverDynamics_dust_FullModelOD_capabilities`)
}

dust_FullModelOD_gpu_info <- function() {
  .Call(`_YellowFeverDynamics_dust_FullModelOD_gpu_info`)
}

dust_cpu_FullModelOD_alloc <- function(r_pars, pars_multi, time, r_n_particles, n_threads, r_seed, deterministic, gpu_config) {
  .Call(`_YellowFeverDynamics_dust_cpu_FullModelOD_alloc`, r_pars, pars_multi, time, r_n_particles, n_threads, r_seed, deterministic, gpu_config)
}

dust_cpu_FullModelOD_run <- function(ptr, time_end) {
  .Call(`_YellowFeverDynamics_dust_cpu_FullModelOD_run`, ptr, time_end)
}

dust_cpu_FullModelOD_simulate <- function(ptr, time_end) {
  .Call(`_YellowFeverDynamics_dust_cpu_FullModelOD_simulate`, ptr, time_end)
}

dust_cpu_FullModelOD_set_index <- function(ptr, r_index) {
  .Call(`_YellowFeverDynamics_dust_cpu_FullModelOD_set_index`, ptr, r_index)
}

dust_cpu_FullModelOD_update_state <- function(ptr, r_pars, r_state, r_time, r_set_initial_state, index, reset_step_size) {
  .Call(`_YellowFeverDynamics_dust_cpu_FullModelOD_update_state`, ptr, r_pars, r_state, r_time, r_set_initial_state, index, reset_step_size)
}

dust_cpu_FullModelOD_state <- function(ptr, r_index) {
  .Call(`_YellowFeverDynamics_dust_cpu_FullModelOD_state`, ptr, r_index)
}

dust_cpu_FullModelOD_time <- function(ptr) {
  .Call(`_YellowFeverDynamics_dust_cpu_FullModelOD_time`, ptr)
}

dust_cpu_FullModelOD_reorder <- function(ptr, r_index) {
  invisible(.Call(`_YellowFeverDynamics_dust_cpu_FullModelOD_reorder`, ptr, r_index))
}

dust_cpu_FullModelOD_resample <- function(ptr, r_weights) {
  .Call(`_YellowFeverDynamics_dust_cpu_FullModelOD_resample`, ptr, r_weights)
}

dust_cpu_FullModelOD_rng_state <- function(ptr, first_only, last_only) {
  .Call(`_YellowFeverDynamics_dust_cpu_FullModelOD_rng_state`, ptr, first_only, last_only)
}

dust_cpu_FullModelOD_set_rng_state <- function(ptr, rng_state) {
  .Call(`_YellowFeverDynamics_dust_cpu_FullModelOD_set_rng_state`, ptr, rng_state)
}

dust_cpu_FullModelOD_set_data <- function(ptr, data, shared) {
  .Call(`_YellowFeverDynamics_dust_cpu_FullModelOD_set_data`, ptr, data, shared)
}

dust_cpu_FullModelOD_compare_data <- function(ptr) {
  .Call(`_YellowFeverDynamics_dust_cpu_FullModelOD_compare_data`, ptr)
}

dust_cpu_FullModelOD_filter <- function(ptr, time_end, save_trajectories, time_snapshot, min_log_likelihood) {
  .Call(`_YellowFeverDynamics_dust_cpu_FullModelOD_filter`, ptr, time_end, save_trajectories, time_snapshot, min_log_likelihood)
}

dust_cpu_FullModelOD_set_n_threads <- function(ptr, n_threads) {
  invisible(.Call(`_YellowFeverDynamics_dust_cpu_FullModelOD_set_n_threads`, ptr, n_threads))
}

dust_cpu_FullModelOD_n_state <- function(ptr) {
  .Call(`_YellowFeverDynamics_dust_cpu_FullModelOD_n_state`, ptr)
}

dust_FullModelODDelay_capabilities <- function() {
  .Call(`_YellowFeverDynamics_dust_FullModelODDelay_capabilities`)
}

dust_FullModelODDelay_gpu_info <- function() {
  .Call(`_YellowFeverDynamics_dust_FullModelODDelay_gpu_info`)
}

dust_cpu_FullModelODDelay_alloc <- function(r_pars, pars_multi, time, r_n_particles, n_threads, r_seed, deterministic, gpu_config) {
  .Call(`_YellowFeverDynamics_dust_cpu_FullModelODDelay_alloc`, r_pars, pars_multi, time, r_n_particles, n_threads, r_seed, deterministic, gpu_config)
}

dust_cpu_FullModelODDelay_run <- function(ptr, time_end) {
  .Call(`_YellowFeverDynamics_dust_cpu_FullModelODDelay_run`, ptr, time_end)
}

dust_cpu_FullModelODDelay_simulate <- function(ptr, time_end) {
  .Call(`_YellowFeverDynamics_dust_cpu_FullModelODDelay_simulate`, ptr, time_end)
}

dust_cpu_FullModelODDelay_set_index <- function(ptr, r_index) {
  .Call(`_YellowFeverDynamics_dust_cpu_FullModelODDelay_set_index`, ptr, r_index)
}

dust_cpu_FullModelODDelay_update_state <- function(ptr, r_pars, r_state, r_time, r_set_initial_state, index, reset_step_size) {
  .Call(`_YellowFeverDynamics_dust_cpu_FullModelODDelay_update_state`, ptr, r_pars, r_state, r_time, r_set_initial_state, index, reset_step_size)
}

dust_cpu_FullModelODDelay_state <- function(ptr, r_index) {
  .Call(`_YellowFeverDynamics_dust_cpu_FullModelODDelay_state`, ptr, r_index)
}

dust_cpu_FullModelODDelay_time <- function(ptr) {
  .Call(`_YellowFeverDynamics_dust_cpu_FullModelODDelay_time`, ptr)
}

dust_cpu_FullModelODDelay_reorder <- function(ptr, r_index) {
  invisible(.Call(`_YellowFeverDynamics_dust_cpu_FullModelODDelay_reorder`, ptr, r_index))
}

dust_cpu_FullModelODDelay_resample <- function(ptr, r_weights) {
  .Call(`_YellowFeverDynamics_dust_cpu_FullModelODDelay_resample`, ptr, r_weights)
}

dust_cpu_FullModelODDelay_rng_state <- function(ptr, first_only, last_only) {
  .Call(`_YellowFeverDynamics_dust_cpu_FullModelODDelay_rng_state`, ptr, first_only, last_only)
}

dust_cpu_FullModelODDelay_set_rng_state <- function(ptr, rng_state) {
  .Call(`_YellowFeverDynamics_dust_cpu_FullModelODDelay_set_rng_state`, ptr, rng_state)
}

dust_cpu_FullModelODDelay_set_data <- function(ptr, data, shared) {
  .Call(`_YellowFeverDynamics_dust_cpu_FullModelODDelay_set_data`, ptr, data, shared)
}

dust_cpu_FullModelODDelay_compare_data <- function(ptr) {
  .Call(`_YellowFeverDynamics_dust_cpu_FullModelODDelay_compare_data`, ptr)
}

dust_cpu_FullModelODDelay_filter <- function(ptr, time_end, save_trajectories, time_snapshot, min_log_likelihood) {
  .Call(`_YellowFeverDynamics_dust_cpu_FullModelODDelay_filter`, ptr, time_end, save_trajectories, time_snapshot, min_log_likelihood)
}

dust_cpu_FullModelODDelay_set_n_threads <- function(ptr, n_threads) {
  invisible(.Call(`_YellowFeverDynamics_dust_cpu_FullModelODDelay_set_n_threads`, ptr, n_threads))
}

dust_cpu_FullModelODDelay_n_state <- function(ptr) {
  .Call(`_YellowFeverDynamics_dust_cpu_FullModelODDelay_n_state`, ptr)
}

dust_FullModelODDeterministic_capabilities <- function() {
  .Call(`_YellowFeverDynamics_dust_FullModelODDeterministic_capabilities`)
}

dust_FullModelODDeterministic_gpu_info <- function() {
  .Call(`_YellowFeverDynamics_dust_FullModelODDeterministic_gpu_info`)
}

dust_cpu_FullModelODDeterministic_alloc <- function(r_pars, pars_multi, time, r_n_particles, n_threads, r_seed, deterministic, gpu_config) {
  .Call(`_YellowFeverDynamics_dust_cpu_FullModelODDeterministic_alloc`, r_pars, pars_multi, time, r_n_particles, n_threads, r_seed, deterministic, gpu_config)
}

dust_cpu_FullModelODDeterministic_run <- function(ptr, time_end) {
  .Call(`_YellowFeverDynamics_dust_cpu_FullModelODDeterministic_run`, ptr, time_end)
}

dust_cpu_FullModelODDeterministic_simulate <- function(ptr, time_end) {
  .Call(`_YellowFeverDynamics_dust_cpu_FullModelODDeterministic_simulate`, ptr, time_end)
}

dust_cpu_FullModelODDeterministic_set_index <- function(ptr, r_index) {
  .Call(`_YellowFeverDynamics_dust_cpu_FullModelODDeterministic_set_index`, ptr, r_index)
}

dust_cpu_FullModelODDeterministic_update_state <- function(ptr, r_pars, r_state, r_time, r_set_initial_state, index, reset_step_size) {
  .Call(`_YellowFeverDynamics_dust_cpu_FullModelODDeterministic_update_state`, ptr, r_pars, r_state, r_time, r_set_initial_state, index, reset_step_size)
}

dust_cpu_FullModelODDeterministic_state <- function(ptr, r_index) {
  .Call(`_YellowFeverDynamics_dust_cpu_FullModelODDeterministic_state`, ptr, r_index)
}

dust_cpu_FullModelODDeterministic_time <- function(ptr) {
  .Call(`_YellowFeverDynamics_dust_cpu_FullModelODDeterministic_time`, ptr)
}

dust_cpu_FullModelODDeterministic_reorder <- function(ptr, r_index) {
  invisible(.Call(`_YellowFeverDynamics_dust_cpu_FullModelODDeterministic_reorder`, ptr, r_index))
}

dust_cpu_FullModelODDeterministic_resample <- function(ptr, r_weights) {
  .Call(`_YellowFeverDynamics_dust_cpu_FullModelODDeterministic_resample`, ptr, r_weights)
}

dust_cpu_FullModelODDeterministic_rng_state <- function(ptr, first_only, last_only) {
  .Call(`_YellowFeverDynamics_dust_cpu_FullModelODDeterministic_rng_state`, ptr, first_only, last_only)
}

dust_cpu_FullModelODDeterministic_set_rng_state <- function(ptr, rng_state) {
  .Call(`_YellowFeverDynamics_dust_cpu_FullModelODDeterministic_set_rng_state`, ptr, rng_state)
}

dust_cpu_FullModelODDeterministic_set_data <- function(ptr, data, shared) {
  .Call(`_YellowFeverDynamics_dust_cpu_FullModelODDeterministic_set_data`, ptr, data, shared)
}

dust_cpu_FullModelODDeterministic_compare_data <- function(ptr) {
  .Call(`_YellowFeverDynamics_dust_cpu_FullModelODDeterministic_compare_data`, ptr)
}

dust_cpu_FullModelODDeterministic_filter <- function(ptr, time_end, save_trajectories, time_snapshot, min_log_likelihood) {
  .Call(`_YellowFeverDynamics_dust_cpu_FullModelODDeterministic_filter`, ptr, time_end, save_trajectories, time_snapshot, min_log_likelihood)
}

dust_cpu_FullModelODDeterministic_set_n_threads <- function(ptr, n_threads) {
  invisible(.Call(`_YellowFeverDynamics_dust_cpu_FullModelODDeterministic_set_n_threads`, ptr, n_threads))
}

dust_cpu_FullModelODDeterministic_n_state <- function(ptr) {
  .Call(`_YellowFeverDynamics_dust_cpu_FullModelODDeterministic_n_state`, ptr)
}

dust_InfectionSplitModelOD_capabilities <- function() {
  .Call(`_YellowFeverDynamics_dust_InfectionSplitModelOD_capabilities`)
}

dust_InfectionSplitModelOD_gpu_info <- function() {
  .Call(`_YellowFeverDynamics_dust_InfectionSplitModelOD_gpu_info`)
}

dust_cpu_InfectionSplitModelOD_alloc <- function(r_pars, pars_multi, time, r_n_particles, n_threads, r_seed, deterministic, gpu_config) {
  .Call(`_YellowFeverDynamics_dust_cpu_InfectionSplitModelOD_alloc`, r_pars, pars_multi, time, r_n_particles, n_threads, r_seed, deterministic, gpu_config)
}

dust_cpu_InfectionSplitModelOD_run <- function(ptr, time_end) {
  .Call(`_YellowFeverDynamics_dust_cpu_InfectionSplitModelOD_run`, ptr, time_end)
}

dust_cpu_InfectionSplitModelOD_simulate <- function(ptr, time_end) {
  .Call(`_YellowFeverDynamics_dust_cpu_InfectionSplitModelOD_simulate`, ptr, time_end)
}

dust_cpu_InfectionSplitModelOD_set_index <- function(ptr, r_index) {
  .Call(`_YellowFeverDynamics_dust_cpu_InfectionSplitModelOD_set_index`, ptr, r_index)
}

dust_cpu_InfectionSplitModelOD_update_state <- function(ptr, r_pars, r_state, r_time, r_set_initial_state, index, reset_step_size) {
  .Call(`_YellowFeverDynamics_dust_cpu_InfectionSplitModelOD_update_state`, ptr, r_pars, r_state, r_time, r_set_initial_state, index, reset_step_size)
}

dust_cpu_InfectionSplitModelOD_state <- function(ptr, r_index) {
  .Call(`_YellowFeverDynamics_dust_cpu_InfectionSplitModelOD_state`, ptr, r_index)
}

dust_cpu_InfectionSplitModelOD_time <- function(ptr) {
  .Call(`_YellowFeverDynamics_dust_cpu_InfectionSplitModelOD_time`, ptr)
}

dust_cpu_InfectionSplitModelOD_reorder <- function(ptr, r_index) {
  invisible(.Call(`_YellowFeverDynamics_dust_cpu_InfectionSplitModelOD_reorder`, ptr, r_index))
}

dust_cpu_InfectionSplitModelOD_resample <- function(ptr, r_weights) {
  .Call(`_YellowFeverDynamics_dust_cpu_InfectionSplitModelOD_resample`, ptr, r_weights)
}

dust_cpu_InfectionSplitModelOD_rng_state <- function(ptr, first_only, last_only) {
  .Call(`_YellowFeverDynamics_dust_cpu_InfectionSplitModelOD_rng_state`, ptr, first_only, last_only)
}

dust_cpu_InfectionSplitModelOD_set_rng_state <- function(ptr, rng_state) {
  .Call(`_YellowFeverDynamics_dust_cpu_InfectionSplitModelOD_set_rng_state`, ptr, rng_state)
}

dust_cpu_InfectionSplitModelOD_set_data <- function(ptr, data, shared) {
  .Call(`_YellowFeverDynamics_dust_cpu_InfectionSplitModelOD_set_data`, ptr, data, shared)
}

dust_cpu_InfectionSplitModelOD_compare_data <- function(ptr) {
  .Call(`_YellowFeverDynamics_dust_cpu_InfectionSplitModelOD_compare_data`, ptr)
}

dust_cpu_InfectionSplitModelOD_filter <- function(ptr, time_end, save_trajectories, time_snapshot, min_log_likelihood) {
  .Call(`_YellowFeverDynamics_dust_cpu_InfectionSplitModelOD_filter`, ptr, time_end, save_trajectories, time_snapshot, min_log_likelihood)
}

dust_cpu_InfectionSplitModelOD_set_n_threads <- function(ptr, n_threads) {
  invisible(.Call(`_YellowFeverDynamics_dust_cpu_InfectionSplitModelOD_set_n_threads`, ptr, n_threads))
}

dust_cpu_InfectionSplitModelOD_n_state <- function(ptr) {
  .Call(`_YellowFeverDynamics_dust_cpu_InfectionSplitModelOD_n_state`, ptr)
}

dust_ReactiveModelOD_capabilities <- function() {
  .Call(`_YellowFeverDynamics_dust_ReactiveModelOD_capabilities`)
}

dust_ReactiveModelOD_gpu_info <- function() {
  .Call(`_YellowFeverDynamics_dust_ReactiveModelOD_gpu_info`)
}

dust_cpu_ReactiveModelOD_alloc <- function(r_pars, pars_multi, time, r_n_particles, n_threads, r_seed, deterministic, gpu_config) {
  .Call(`_YellowFeverDynamics_dust_cpu_ReactiveModelOD_alloc`, r_pars, pars_multi, time, r_n_particles, n_threads, r_seed, deterministic, gpu_config)
}

dust_cpu_ReactiveModelOD_run <- function(ptr, time_end) {
  .Call(`_YellowFeverDynamics_dust_cpu_ReactiveModelOD_run`, ptr, time_end)
}

dust_cpu_ReactiveModelOD_simulate <- function(ptr, time_end) {
  .Call(`_YellowFeverDynamics_dust_cpu_ReactiveModelOD_simulate`, ptr, time_end)
}

dust_cpu_ReactiveModelOD_set_index <- function(ptr, r_index) {
  .Call(`_YellowFeverDynamics_dust_cpu_ReactiveModelOD_set_index`, ptr, r_index)
}

dust_cpu_ReactiveModelOD_update_state <- function(ptr, r_pars, r_state, r_time, r_set_initial_state, index, reset_step_size) {
  .Call(`_YellowFeverDynamics_dust_cpu_ReactiveModelOD_update_state`, ptr, r_pars, r_state, r_time, r_set_initial_state, index, reset_step_size)
}

dust_cpu_ReactiveModelOD_state <- function(ptr, r_index) {
  .Call(`_YellowFeverDynamics_dust_cpu_ReactiveModelOD_state`, ptr, r_index)
}

dust_cpu_ReactiveModelOD_time <- function(ptr) {
  .Call(`_YellowFeverDynamics_dust_cpu_ReactiveModelOD_time`, ptr)
}

dust_cpu_ReactiveModelOD_reorder <- function(ptr, r_index) {
  invisible(.Call(`_YellowFeverDynamics_dust_cpu_ReactiveModelOD_reorder`, ptr, r_index))
}

dust_cpu_ReactiveModelOD_resample <- function(ptr, r_weights) {
  .Call(`_YellowFeverDynamics_dust_cpu_ReactiveModelOD_resample`, ptr, r_weights)
}

dust_cpu_ReactiveModelOD_rng_state <- function(ptr, first_only, last_only) {
  .Call(`_YellowFeverDynamics_dust_cpu_ReactiveModelOD_rng_state`, ptr, first_only, last_only)
}

dust_cpu_ReactiveModelOD_set_rng_state <- function(ptr, rng_state) {
  .Call(`_YellowFeverDynamics_dust_cpu_ReactiveModelOD_set_rng_state`, ptr, rng_state)
}

dust_cpu_ReactiveModelOD_set_data <- function(ptr, data, shared) {
  .Call(`_YellowFeverDynamics_dust_cpu_ReactiveModelOD_set_data`, ptr, data, shared)
}

dust_cpu_ReactiveModelOD_compare_data <- function(ptr) {
  .Call(`_YellowFeverDynamics_dust_cpu_ReactiveModelOD_compare_data`, ptr)
}

dust_cpu_ReactiveModelOD_filter <- function(ptr, time_end, save_trajectories, time_snapshot, min_log_likelihood) {
  .Call(`_YellowFeverDynamics_dust_cpu_ReactiveModelOD_filter`, ptr, time_end, save_trajectories, time_snapshot, min_log_likelihood)
}

dust_cpu_ReactiveModelOD_set_n_threads <- function(ptr, n_threads) {
  invisible(.Call(`_YellowFeverDynamics_dust_cpu_ReactiveModelOD_set_n_threads`, ptr, n_threads))
}

dust_cpu_ReactiveModelOD_n_state <- function(ptr) {
  .Call(`_YellowFeverDynamics_dust_cpu_ReactiveModelOD_n_state`, ptr)
}
