# Generated by cpp11: do not edit by hand

dust_SEIRVModelDelay_gpu_info <- function() {
  .Call(`_YellowFeverDynamics_dust_SEIRVModelDelay_gpu_info`)
}

dust_cpu_SEIRVModelDelay_alloc <- function(r_pars, pars_multi, r_time, r_n_particles, n_threads, r_seed, deterministic, gpu_config, ode_control) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelDelay_alloc`, r_pars, pars_multi, r_time, r_n_particles, n_threads, r_seed, deterministic, gpu_config, ode_control)
}

dust_cpu_SEIRVModelDelay_capabilities <- function() {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelDelay_capabilities`)
}

dust_cpu_SEIRVModelDelay_run <- function(ptr, r_time_end) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelDelay_run`, ptr, r_time_end)
}

dust_cpu_SEIRVModelDelay_simulate <- function(ptr, time_end) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelDelay_simulate`, ptr, time_end)
}

dust_cpu_SEIRVModelDelay_set_index <- function(ptr, r_index) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelDelay_set_index`, ptr, r_index)
}

dust_cpu_SEIRVModelDelay_update_state <- function(ptr, r_pars, r_state, r_time, r_set_initial_state, index, reset_step_size) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelDelay_update_state`, ptr, r_pars, r_state, r_time, r_set_initial_state, index, reset_step_size)
}

dust_cpu_SEIRVModelDelay_state <- function(ptr, r_index) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelDelay_state`, ptr, r_index)
}

dust_cpu_SEIRVModelDelay_time <- function(ptr) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelDelay_time`, ptr)
}

dust_cpu_SEIRVModelDelay_reorder <- function(ptr, r_index) {
  invisible(.Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelDelay_reorder`, ptr, r_index))
}

dust_cpu_SEIRVModelDelay_resample <- function(ptr, r_weights) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelDelay_resample`, ptr, r_weights)
}

dust_cpu_SEIRVModelDelay_rng_state <- function(ptr, first_only, last_only) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelDelay_rng_state`, ptr, first_only, last_only)
}

dust_cpu_SEIRVModelDelay_set_rng_state <- function(ptr, rng_state) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelDelay_set_rng_state`, ptr, rng_state)
}

dust_cpu_SEIRVModelDelay_set_data <- function(ptr, data, shared) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelDelay_set_data`, ptr, data, shared)
}

dust_cpu_SEIRVModelDelay_compare_data <- function(ptr) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelDelay_compare_data`, ptr)
}

dust_cpu_SEIRVModelDelay_filter <- function(ptr, time_end, save_trajectories, time_snapshot, min_log_likelihood) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelDelay_filter`, ptr, time_end, save_trajectories, time_snapshot, min_log_likelihood)
}

dust_cpu_SEIRVModelDelay_set_n_threads <- function(ptr, n_threads) {
  invisible(.Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelDelay_set_n_threads`, ptr, n_threads))
}

dust_cpu_SEIRVModelDelay_n_state <- function(ptr) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelDelay_n_state`, ptr)
}

dust_cpu_SEIRVModelDelay_set_stochastic_schedule <- function(ptr, time) {
  invisible(.Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelDelay_set_stochastic_schedule`, ptr, time))
}

dust_cpu_SEIRVModelDelay_ode_statistics <- function(ptr) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelDelay_ode_statistics`, ptr)
}

dust_SEIRVModelReactive_gpu_info <- function() {
  .Call(`_YellowFeverDynamics_dust_SEIRVModelReactive_gpu_info`)
}

dust_cpu_SEIRVModelReactive_alloc <- function(r_pars, pars_multi, r_time, r_n_particles, n_threads, r_seed, deterministic, gpu_config, ode_control) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelReactive_alloc`, r_pars, pars_multi, r_time, r_n_particles, n_threads, r_seed, deterministic, gpu_config, ode_control)
}

dust_cpu_SEIRVModelReactive_capabilities <- function() {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelReactive_capabilities`)
}

dust_cpu_SEIRVModelReactive_run <- function(ptr, r_time_end) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelReactive_run`, ptr, r_time_end)
}

dust_cpu_SEIRVModelReactive_simulate <- function(ptr, time_end) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelReactive_simulate`, ptr, time_end)
}

dust_cpu_SEIRVModelReactive_set_index <- function(ptr, r_index) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelReactive_set_index`, ptr, r_index)
}

dust_cpu_SEIRVModelReactive_update_state <- function(ptr, r_pars, r_state, r_time, r_set_initial_state, index, reset_step_size) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelReactive_update_state`, ptr, r_pars, r_state, r_time, r_set_initial_state, index, reset_step_size)
}

dust_cpu_SEIRVModelReactive_state <- function(ptr, r_index) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelReactive_state`, ptr, r_index)
}

dust_cpu_SEIRVModelReactive_time <- function(ptr) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelReactive_time`, ptr)
}

dust_cpu_SEIRVModelReactive_reorder <- function(ptr, r_index) {
  invisible(.Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelReactive_reorder`, ptr, r_index))
}

dust_cpu_SEIRVModelReactive_resample <- function(ptr, r_weights) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelReactive_resample`, ptr, r_weights)
}

dust_cpu_SEIRVModelReactive_rng_state <- function(ptr, first_only, last_only) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelReactive_rng_state`, ptr, first_only, last_only)
}

dust_cpu_SEIRVModelReactive_set_rng_state <- function(ptr, rng_state) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelReactive_set_rng_state`, ptr, rng_state)
}

dust_cpu_SEIRVModelReactive_set_data <- function(ptr, data, shared) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelReactive_set_data`, ptr, data, shared)
}

dust_cpu_SEIRVModelReactive_compare_data <- function(ptr) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelReactive_compare_data`, ptr)
}

dust_cpu_SEIRVModelReactive_filter <- function(ptr, time_end, save_trajectories, time_snapshot, min_log_likelihood) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelReactive_filter`, ptr, time_end, save_trajectories, time_snapshot, min_log_likelihood)
}

dust_cpu_SEIRVModelReactive_set_n_threads <- function(ptr, n_threads) {
  invisible(.Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelReactive_set_n_threads`, ptr, n_threads))
}

dust_cpu_SEIRVModelReactive_n_state <- function(ptr) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelReactive_n_state`, ptr)
}

dust_cpu_SEIRVModelReactive_set_stochastic_schedule <- function(ptr, time) {
  invisible(.Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelReactive_set_stochastic_schedule`, ptr, time))
}

dust_cpu_SEIRVModelReactive_ode_statistics <- function(ptr) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelReactive_ode_statistics`, ptr)
}

dust_SEIRVModelSplitInfection_gpu_info <- function() {
  .Call(`_YellowFeverDynamics_dust_SEIRVModelSplitInfection_gpu_info`)
}

dust_cpu_SEIRVModelSplitInfection_alloc <- function(r_pars, pars_multi, r_time, r_n_particles, n_threads, r_seed, deterministic, gpu_config, ode_control) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelSplitInfection_alloc`, r_pars, pars_multi, r_time, r_n_particles, n_threads, r_seed, deterministic, gpu_config, ode_control)
}

dust_cpu_SEIRVModelSplitInfection_capabilities <- function() {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelSplitInfection_capabilities`)
}

dust_cpu_SEIRVModelSplitInfection_run <- function(ptr, r_time_end) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelSplitInfection_run`, ptr, r_time_end)
}

dust_cpu_SEIRVModelSplitInfection_simulate <- function(ptr, time_end) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelSplitInfection_simulate`, ptr, time_end)
}

dust_cpu_SEIRVModelSplitInfection_set_index <- function(ptr, r_index) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelSplitInfection_set_index`, ptr, r_index)
}

dust_cpu_SEIRVModelSplitInfection_update_state <- function(ptr, r_pars, r_state, r_time, r_set_initial_state, index, reset_step_size) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelSplitInfection_update_state`, ptr, r_pars, r_state, r_time, r_set_initial_state, index, reset_step_size)
}

dust_cpu_SEIRVModelSplitInfection_state <- function(ptr, r_index) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelSplitInfection_state`, ptr, r_index)
}

dust_cpu_SEIRVModelSplitInfection_time <- function(ptr) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelSplitInfection_time`, ptr)
}

dust_cpu_SEIRVModelSplitInfection_reorder <- function(ptr, r_index) {
  invisible(.Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelSplitInfection_reorder`, ptr, r_index))
}

dust_cpu_SEIRVModelSplitInfection_resample <- function(ptr, r_weights) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelSplitInfection_resample`, ptr, r_weights)
}

dust_cpu_SEIRVModelSplitInfection_rng_state <- function(ptr, first_only, last_only) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelSplitInfection_rng_state`, ptr, first_only, last_only)
}

dust_cpu_SEIRVModelSplitInfection_set_rng_state <- function(ptr, rng_state) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelSplitInfection_set_rng_state`, ptr, rng_state)
}

dust_cpu_SEIRVModelSplitInfection_set_data <- function(ptr, data, shared) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelSplitInfection_set_data`, ptr, data, shared)
}

dust_cpu_SEIRVModelSplitInfection_compare_data <- function(ptr) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelSplitInfection_compare_data`, ptr)
}

dust_cpu_SEIRVModelSplitInfection_filter <- function(ptr, time_end, save_trajectories, time_snapshot, min_log_likelihood) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelSplitInfection_filter`, ptr, time_end, save_trajectories, time_snapshot, min_log_likelihood)
}

dust_cpu_SEIRVModelSplitInfection_set_n_threads <- function(ptr, n_threads) {
  invisible(.Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelSplitInfection_set_n_threads`, ptr, n_threads))
}

dust_cpu_SEIRVModelSplitInfection_n_state <- function(ptr) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelSplitInfection_n_state`, ptr)
}

dust_cpu_SEIRVModelSplitInfection_set_stochastic_schedule <- function(ptr, time) {
  invisible(.Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelSplitInfection_set_stochastic_schedule`, ptr, time))
}

dust_cpu_SEIRVModelSplitInfection_ode_statistics <- function(ptr) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelSplitInfection_ode_statistics`, ptr)
}

dust_SEIRVModelVarFR_gpu_info <- function() {
  .Call(`_YellowFeverDynamics_dust_SEIRVModelVarFR_gpu_info`)
}

dust_cpu_SEIRVModelVarFR_alloc <- function(r_pars, pars_multi, r_time, r_n_particles, n_threads, r_seed, deterministic, gpu_config, ode_control) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelVarFR_alloc`, r_pars, pars_multi, r_time, r_n_particles, n_threads, r_seed, deterministic, gpu_config, ode_control)
}

dust_cpu_SEIRVModelVarFR_capabilities <- function() {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelVarFR_capabilities`)
}

dust_cpu_SEIRVModelVarFR_run <- function(ptr, r_time_end) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelVarFR_run`, ptr, r_time_end)
}

dust_cpu_SEIRVModelVarFR_simulate <- function(ptr, time_end) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelVarFR_simulate`, ptr, time_end)
}

dust_cpu_SEIRVModelVarFR_set_index <- function(ptr, r_index) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelVarFR_set_index`, ptr, r_index)
}

dust_cpu_SEIRVModelVarFR_update_state <- function(ptr, r_pars, r_state, r_time, r_set_initial_state, index, reset_step_size) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelVarFR_update_state`, ptr, r_pars, r_state, r_time, r_set_initial_state, index, reset_step_size)
}

dust_cpu_SEIRVModelVarFR_state <- function(ptr, r_index) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelVarFR_state`, ptr, r_index)
}

dust_cpu_SEIRVModelVarFR_time <- function(ptr) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelVarFR_time`, ptr)
}

dust_cpu_SEIRVModelVarFR_reorder <- function(ptr, r_index) {
  invisible(.Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelVarFR_reorder`, ptr, r_index))
}

dust_cpu_SEIRVModelVarFR_resample <- function(ptr, r_weights) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelVarFR_resample`, ptr, r_weights)
}

dust_cpu_SEIRVModelVarFR_rng_state <- function(ptr, first_only, last_only) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelVarFR_rng_state`, ptr, first_only, last_only)
}

dust_cpu_SEIRVModelVarFR_set_rng_state <- function(ptr, rng_state) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelVarFR_set_rng_state`, ptr, rng_state)
}

dust_cpu_SEIRVModelVarFR_set_data <- function(ptr, data, shared) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelVarFR_set_data`, ptr, data, shared)
}

dust_cpu_SEIRVModelVarFR_compare_data <- function(ptr) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelVarFR_compare_data`, ptr)
}

dust_cpu_SEIRVModelVarFR_filter <- function(ptr, time_end, save_trajectories, time_snapshot, min_log_likelihood) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelVarFR_filter`, ptr, time_end, save_trajectories, time_snapshot, min_log_likelihood)
}

dust_cpu_SEIRVModelVarFR_set_n_threads <- function(ptr, n_threads) {
  invisible(.Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelVarFR_set_n_threads`, ptr, n_threads))
}

dust_cpu_SEIRVModelVarFR_n_state <- function(ptr) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelVarFR_n_state`, ptr)
}

dust_cpu_SEIRVModelVarFR_set_stochastic_schedule <- function(ptr, time) {
  invisible(.Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelVarFR_set_stochastic_schedule`, ptr, time))
}

dust_cpu_SEIRVModelVarFR_ode_statistics <- function(ptr) {
  .Call(`_YellowFeverDynamics_dust_cpu_SEIRVModelVarFR_ode_statistics`, ptr)
}
