# Generated by cpp11: do not edit by hand

dust_BasicModelOD_alloc <- function(r_pars, pars_multi, step, r_n_particles, n_threads, r_seed, device_id) {
  .Call(`_YellowFeverDynamics_dust_BasicModelOD_alloc`, r_pars, pars_multi, step, r_n_particles, n_threads, r_seed, device_id)
}

dust_BasicModelOD_run <- function(ptr, step_end, device) {
  .Call(`_YellowFeverDynamics_dust_BasicModelOD_run`, ptr, step_end, device)
}

dust_BasicModelOD_simulate <- function(ptr, step_end, device) {
  .Call(`_YellowFeverDynamics_dust_BasicModelOD_simulate`, ptr, step_end, device)
}

dust_BasicModelOD_set_index <- function(ptr, r_index) {
  .Call(`_YellowFeverDynamics_dust_BasicModelOD_set_index`, ptr, r_index)
}

dust_BasicModelOD_set_state <- function(ptr, r_state, r_step) {
  .Call(`_YellowFeverDynamics_dust_BasicModelOD_set_state`, ptr, r_state, r_step)
}

dust_BasicModelOD_reset <- function(ptr, r_pars, step) {
  .Call(`_YellowFeverDynamics_dust_BasicModelOD_reset`, ptr, r_pars, step)
}

dust_BasicModelOD_state <- function(ptr, r_index) {
  .Call(`_YellowFeverDynamics_dust_BasicModelOD_state`, ptr, r_index)
}

dust_BasicModelOD_step <- function(ptr) {
  .Call(`_YellowFeverDynamics_dust_BasicModelOD_step`, ptr)
}

dust_BasicModelOD_reorder <- function(ptr, r_index) {
  invisible(.Call(`_YellowFeverDynamics_dust_BasicModelOD_reorder`, ptr, r_index))
}

dust_BasicModelOD_resample <- function(ptr, r_weights) {
  .Call(`_YellowFeverDynamics_dust_BasicModelOD_resample`, ptr, r_weights)
}

dust_BasicModelOD_set_pars <- function(ptr, r_pars) {
  .Call(`_YellowFeverDynamics_dust_BasicModelOD_set_pars`, ptr, r_pars)
}

dust_BasicModelOD_rng_state <- function(ptr, first_only, last_only) {
  .Call(`_YellowFeverDynamics_dust_BasicModelOD_rng_state`, ptr, first_only, last_only)
}

dust_BasicModelOD_set_rng_state <- function(ptr, rng_state) {
  .Call(`_YellowFeverDynamics_dust_BasicModelOD_set_rng_state`, ptr, rng_state)
}

dust_BasicModelOD_set_data <- function(ptr, data) {
  .Call(`_YellowFeverDynamics_dust_BasicModelOD_set_data`, ptr, data)
}

dust_BasicModelOD_compare_data <- function(ptr, device) {
  .Call(`_YellowFeverDynamics_dust_BasicModelOD_compare_data`, ptr, device)
}

dust_BasicModelOD_filter <- function(ptr, save_trajectories, step_snapshot, device) {
  .Call(`_YellowFeverDynamics_dust_BasicModelOD_filter`, ptr, save_trajectories, step_snapshot, device)
}

dust_BasicModelOD_capabilities <- function() {
  .Call(`_YellowFeverDynamics_dust_BasicModelOD_capabilities`)
}

dust_BasicModelOD_set_n_threads <- function(ptr, n_threads) {
  invisible(.Call(`_YellowFeverDynamics_dust_BasicModelOD_set_n_threads`, ptr, n_threads))
}

dust_BasicModelOD_n_state <- function(ptr) {
  .Call(`_YellowFeverDynamics_dust_BasicModelOD_n_state`, ptr)
}

dust_BasicModelOD_device_info <- function() {
  .Call(`_YellowFeverDynamics_dust_BasicModelOD_device_info`)
}

dust_FullModelOD_alloc <- function(r_pars, pars_multi, step, r_n_particles, n_threads, r_seed, device_id) {
  .Call(`_YellowFeverDynamics_dust_FullModelOD_alloc`, r_pars, pars_multi, step, r_n_particles, n_threads, r_seed, device_id)
}

dust_FullModelOD_run <- function(ptr, step_end, device) {
  .Call(`_YellowFeverDynamics_dust_FullModelOD_run`, ptr, step_end, device)
}

dust_FullModelOD_simulate <- function(ptr, step_end, device) {
  .Call(`_YellowFeverDynamics_dust_FullModelOD_simulate`, ptr, step_end, device)
}

dust_FullModelOD_set_index <- function(ptr, r_index) {
  .Call(`_YellowFeverDynamics_dust_FullModelOD_set_index`, ptr, r_index)
}

dust_FullModelOD_set_state <- function(ptr, r_state, r_step) {
  .Call(`_YellowFeverDynamics_dust_FullModelOD_set_state`, ptr, r_state, r_step)
}

dust_FullModelOD_reset <- function(ptr, r_pars, step) {
  .Call(`_YellowFeverDynamics_dust_FullModelOD_reset`, ptr, r_pars, step)
}

dust_FullModelOD_state <- function(ptr, r_index) {
  .Call(`_YellowFeverDynamics_dust_FullModelOD_state`, ptr, r_index)
}

dust_FullModelOD_step <- function(ptr) {
  .Call(`_YellowFeverDynamics_dust_FullModelOD_step`, ptr)
}

dust_FullModelOD_reorder <- function(ptr, r_index) {
  invisible(.Call(`_YellowFeverDynamics_dust_FullModelOD_reorder`, ptr, r_index))
}

dust_FullModelOD_resample <- function(ptr, r_weights) {
  .Call(`_YellowFeverDynamics_dust_FullModelOD_resample`, ptr, r_weights)
}

dust_FullModelOD_set_pars <- function(ptr, r_pars) {
  .Call(`_YellowFeverDynamics_dust_FullModelOD_set_pars`, ptr, r_pars)
}

dust_FullModelOD_rng_state <- function(ptr, first_only, last_only) {
  .Call(`_YellowFeverDynamics_dust_FullModelOD_rng_state`, ptr, first_only, last_only)
}

dust_FullModelOD_set_rng_state <- function(ptr, rng_state) {
  .Call(`_YellowFeverDynamics_dust_FullModelOD_set_rng_state`, ptr, rng_state)
}

dust_FullModelOD_set_data <- function(ptr, data) {
  .Call(`_YellowFeverDynamics_dust_FullModelOD_set_data`, ptr, data)
}

dust_FullModelOD_compare_data <- function(ptr, device) {
  .Call(`_YellowFeverDynamics_dust_FullModelOD_compare_data`, ptr, device)
}

dust_FullModelOD_filter <- function(ptr, save_trajectories, step_snapshot, device) {
  .Call(`_YellowFeverDynamics_dust_FullModelOD_filter`, ptr, save_trajectories, step_snapshot, device)
}

dust_FullModelOD_capabilities <- function() {
  .Call(`_YellowFeverDynamics_dust_FullModelOD_capabilities`)
}

dust_FullModelOD_set_n_threads <- function(ptr, n_threads) {
  invisible(.Call(`_YellowFeverDynamics_dust_FullModelOD_set_n_threads`, ptr, n_threads))
}

dust_FullModelOD_n_state <- function(ptr) {
  .Call(`_YellowFeverDynamics_dust_FullModelOD_n_state`, ptr)
}

dust_FullModelOD_device_info <- function() {
  .Call(`_YellowFeverDynamics_dust_FullModelOD_device_info`)
}
