## Generated by dust2 (version 0.3.22) - do not edit
SEIRModelVtrack <- structure(
  function() get("SEIRModelVtrack"),
  class = "dust_system_generator",
  name = "SEIRModelVtrack",
  package = "YellowFeverDynamics",
  path = NULL,
  parameters = data.frame(
    name = c("time_inc", "t_incubation", "t_latent", "t_infectious", "FOI_spillover", "R0", "N_age", "vacc_rate_daily", "vaccine_efficacy", "year0", "S_0", "E_0", "I_0", "R_0", "dP1_all", "dP2_all", "n_years", "n_t_pts"),
    type = c("real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "int", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "int", "int"),
    constant = c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE),
    required = c(TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE),
    rank = c(0L, 0L, 0L, 0L, 1L, 1L, 0L, 2L, 0L, 0L, 2L, 2L, 2L, 2L, 2L, 2L, 0L, 0L)),
  properties = list(
    time_type = "discrete",
    has_compare = FALSE,
    has_adjoint = FALSE),
  default_dt = 1)
SEIRVModelDelay <- structure(
  function() get("SEIRVModelDelay"),
  class = "dust_system_generator",
  name = "SEIRVModelDelay",
  package = "YellowFeverDynamics",
  path = NULL,
  parameters = data.frame(
    name = c("time_inc", "t_infectious", "FOI_spillover", "R0", "N_age", "vacc_rate_daily", "vaccine_efficacy", "year0", "S_0", "E_0", "E_delay0", "I_0", "I_delay0", "R_0", "V_0", "dP1_all", "dP2_all", "n_years", "n_t_pts", "np_E_delay", "np_I_delay"),
    type = c("real_type", "real_type", "real_type", "real_type", "int", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "int", "int", "int", "int"),
    constant = c(FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, TRUE),
    required = c(TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE),
    rank = c(0L, 0L, 1L, 1L, 0L, 2L, 0L, 0L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 2L, 2L, 0L, 0L, 0L, 0L)),
  properties = list(
    time_type = "discrete",
    has_compare = FALSE,
    has_adjoint = FALSE),
  default_dt = 1)
SEIRVModelDelayReactive <- structure(
  function() get("SEIRVModelDelayReactive"),
  class = "dust_system_generator",
  name = "SEIRVModelDelayReactive",
  package = "YellowFeverDynamics",
  path = NULL,
  parameters = data.frame(
    name = c("time_inc", "t_infectious", "FOI_spillover", "R0", "N_age", "vacc_rate_daily", "vaccine_efficacy", "response_delay", "p_rep", "case_threshold", "cluster_threshold", "vacc_cov_cam", "t_cam", "year0", "S_0", "E_0", "E_delay0", "I_0", "I_delay0", "R_0", "V_0", "dP1_all", "dP2_all", "n_years", "n_t_pts", "np_E_delay", "np_I_delay"),
    type = c("real_type", "real_type", "real_type", "real_type", "int", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "int", "int", "int", "int"),
    constant = c(FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, TRUE),
    required = c(TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE),
    rank = c(0L, 0L, 1L, 1L, 0L, 2L, 0L, 0L, 1L, 0L, 0L, 1L, 0L, 0L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 2L, 2L, 0L, 0L, 0L, 0L)),
  properties = list(
    time_type = "discrete",
    has_compare = FALSE,
    has_adjoint = FALSE),
  default_dt = 1)
SEIRVModelSplitInfection <- structure(
  function() get("SEIRVModelSplitInfection"),
  class = "dust_system_generator",
  name = "SEIRVModelSplitInfection",
  package = "YellowFeverDynamics",
  path = NULL,
  parameters = data.frame(
    name = c("time_inc", "t_incubation", "t_latent", "t_infectious", "FOI_spillover", "R0", "N_age", "vacc_rate_daily", "vaccine_efficacy", "year0", "S_0", "E_0", "I_0", "R_0", "V_0", "dP1_all", "dP2_all", "n_years", "n_t_pts"),
    type = c("real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "int", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "int", "int"),
    constant = c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE),
    required = c(TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE),
    rank = c(0L, 0L, 0L, 0L, 1L, 1L, 0L, 2L, 0L, 0L, 1L, 1L, 1L, 1L, 1L, 2L, 2L, 0L, 0L)),
  properties = list(
    time_type = "discrete",
    has_compare = FALSE,
    has_adjoint = FALSE),
  default_dt = 1)
